# docker build -t jmaclean/jenkins-jnlp-slave:3.40-1 -f Dockerfile.jenkins-jnlp-slave .
FROM jenkins/jnlp-slave:3.40-1

LABEL description="Patched official jnlp-slave build for Jenkins (incl OpenShift)"
LABEL maintainer="Jerome Mac Lean - CrossLogic Consulting"

USER root

RUN chown -R 1000:0 $HOME && \
    chmod -R g+rw $HOME

USER 1000
