version: "3.7"

services:
  jenkins-builder:
    hostname: jenkins-builder
    container_name: jenkins-builder
    build:
      context: ./base/jenkins-builder/
      dockerfile: Dockerfile
    image: jmaclean/jenkins-builder:0.5.7
    # image: r.j3ss.co/img
    security_opt:
      - apparmor:unconfined
      # - seccomp:unconfined
    volumes:
      - .:/app
    entrypoint:
      - tail
      - -f
      - /dev/null
