// ------------------------
// Shared Library Functions
// ------------------------
// Implicitly loaded in the project Folder

def debugInfo

pipeline {
  triggers {
    pollSCM('* * * * *') /* default: poll once a minute */
  }

  options {
    buildDiscarder(
      logRotator(
        artifactDaysToKeepStr: '', 
        artifactNumToKeepStr: '5', 
        daysToKeepStr: '', 
        numToKeepStr: '5'
      )
    )
    timestamps()
  }

  environment {
    GIT_AUTHOR_NAME = sh(returnStdout: true, script: 'git show -s --pretty=%an').trim()
  }

  agent {
    kubernetes(k8sagent(name: 'base+s_helper', label: 'jnlp', cloud: 'kubernetes'))
  }

  stages {
    stage ('Set environment') {
      agent { label 'master' }
      environment {
        TMP_TAGS_NAME = "${TAG_NAME ? TAG_NAME : ''}"
        TMP_CHANGE_ID = "${CHANGE_ID ? CHANGE_ID : ''}"
        BASE_DIR = sh(returnStdout: true, script: "echo ${WORKSPACE} | sed -e 's?.*/workspace/??g' | sed -e 's?/??g'").trim()
        WORKSPACE_LIBS = sh(returnStdout: true, script: "[ -d ${WORKSPACE}/../workspace@libs ] && echo \"${WORKSPACE}/../workspace@libs\" || echo \"${WORKSPACE}/../${BASE_DIR}@libs\"").trim()
        PREP_LOAD_ENV = sh(returnStdout: false, script: "${WORKSPACE_LIBS}/cicd/resources/com/cicd/jenkins/prepEnv.sh -git_commit ${GIT_COMMIT} -tag_name ${TMP_TAGS_NAME} -change_id ${TMP_CHANGE_ID} > /dev/null 2>&1")
      }
      steps {
        sh 'echo "master - Set environment"'
        load "${WORKSPACE_LIBS}/cicd/resources/com/cicd/jenkins/files/env.groovy"

        // script {
        //   if (env.CICD_DEBUG == '1') {
        //     debugInfo = sh(script: "printenv | sort", returnStdout: true)
        //     echo "DEBUG: Environment\n${debugInfo}"
        //   }
        // }
        sh 'printenv | sort'
      }
    }
    stage ('Build Image') {
      when { environment name: 'CICD_BUILD_ENABLED', value: '1' }
      steps {
        container ('jenkins-builder') {
          sh 'echo "jenkins-builder - Build Image"'
          sh 'img build -f Dockerfile -t ${CICD_REGISTRY_URL}/${CICD_REGISTRY_SPACE}/${APP_NAME}:${CICD_TAGS_ID} .'
        }
      }
    }
    stage ('Publish Image') {
      when { environment name: 'CICD_BUILD_ENABLED', value: '1' }
      steps {
        sh 'echo "Push Image"'
      }
    }
  // stages
  }

  post {
    always {
      echo 'This will always run'
    }
    success {
      echo 'This will run only if successful'
    }
    failure {
      echo 'This will run only if failed'
    }
    unstable {
      echo 'This will run only if the run was marked as unstable'
    }
    changed {
      echo 'This will run only if the state of the Pipeline has changed'
      echo 'For example, if the Pipeline was previously failing but is now successful'
    }
  // post
  }

// pipeline
}
