appName: 'Multi App pipeline. appName taken from tag'
loglevel: 'TRACE'
job:
  throttle: 5
config:
  build:
    buildEnvironment: 'test'
  pr:
    buildEnabled: 1
    deployEnabled: 0
    buildEnvironment: 'dev'
  environments:
    generic:
      appNamePrefix: 'jenkins-'
      appNamePostfix: '-helper'
      agent:
        # name: 's_helper+ephemeral_storage'
        name: 's_helper'
    dev:
      name: 'Development'
      platformName: 'Local'
      platformOwner: 'CrossLogic'
      platformNamespace: 'na'

      gitUrl: 'https://github.com'
      gitSpace: 'TBD'
      gitCredentials: 'github.main.cicd.api.credentials'
      registryType: 'docker'
      registryUrl: 'registry.hub.docker.com'
      registrySpace: 'jmaclean'
      registryCredentials: 'registry.dockerhub.cicd.api.credentials'